<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.1 (Python 3.9.13 on linux)" generated="20221111 08:01:50.818" rpa="true" schemaversion="2">
<suite id="s1" name="Upload File To Aws S3" source="/home/light/Desktop/Learn_Python/RPA/src_robot/Cloud/upload_file_to_aws_s3.robot">
<test id="s1-t1" name="Upload a file into S3 bucket">
<kw name="Init S3 Client" type="SETUP">
<arg>aws_key_id=${AWS_KEY_ID}</arg>
<arg>aws_key=${AWS_KEY}</arg>
<msg timestamp="20221111 08:01:50.842" level="FAIL">No keyword with name 'Init S3 Client' found.</msg>
<status status="FAIL" starttime="20221111 08:01:50.842" endtime="20221111 08:01:50.842"/>
</kw>
<status status="FAIL" starttime="20221111 08:01:50.840" endtime="20221111 08:01:50.843">Setup failed:
No keyword with name 'Init S3 Client' found.</status>
</test>
<status status="FAIL" starttime="20221111 08:01:50.820" endtime="20221111 08:01:50.844"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tasks</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Upload File To Aws S3">Upload File To Aws S3</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20221111 08:01:50.839" level="ERROR">Error in file '/home/light/Desktop/Learn_Python/RPA/src_robot/Cloud/upload_file_to_aws_s3.robot' on line 2: Importing library 'RPA.Cloud.AWS' failed: ModuleNotFoundError: No module named 'RPA.Cloud'
Traceback (most recent call last):
  None
PYTHONPATH:
  /home/light/.vscode/extensions/robocorp.robotframework-lsp-1.5.0/src/robotframework_debug_adapter
  /home/light/Desktop/Learn_Python/RPA
  /home/light/.vscode/extensions/robocorp.robotframework-lsp-1.5.0/src
  /home/light/.vscode/extensions/robocorp.robotframework-lsp-1.5.0/src/robotframework_ls/vendored
  /home/light/.robocorp/holotree/e79cca9_b1f3c24_dfaed771/lib/python39.zip
  /home/light/.robocorp/holotree/e79cca9_b1f3c24_dfaed771/lib/python3.9
  /home/light/.robocorp/holotree/e79cca9_b1f3c24_dfaed771/lib/python3.9/lib-dynload
  /home/light/.robocorp/holotree/e79cca9_b1f3c24_dfaed771/lib/python3.9/site-packages</msg>
</errors>
</robot>
